### PR TITLE
Aajinkya2

### PR DESCRIPTION
**Pull request by aajinkya1203**
did a lot of JS of course and other stuff.
check it out will ya!

### CODE REVIEW

**Comment by NecronizerFTW** [comment]
Why is the bottom portion empty?
image

**Comment by NecronizerFTW** [comment]
@pushpit-J19 Work with @aajinkya1203 to make it responsive. Complete it by next week Sunday.

**Comment by necronizer** [comment]
One last bug. When I am switching to some other chat, the messages from the previous chat still remains. Is that possible to fix or should I try to fix it?

**Comment by necronizer** [comment]
Last request. Just fix the variable names and that's all

**Comment by necronizer** [comment]
Because I need to understand what I am handling there

**Pull request merged**
